services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      # - USERNAME=root
    # env_file:
    #   - fileName
    #   - fileName2
    container_name: mongodb
  backend:
    build: ./backend
    # build: 
      # context: ./backend
      # dockerfile: Dockerfile
      # args:
        # some-args: hi
    container_name: backend
    ports:
      - "80:80"
    volumes:
      - logs:/app_6/logs
      - ./backend:/app_6
      - /app_6/node_modules
    env_file:
      - ./backend/env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app_6/src
    stdin_open: true
    tty: true

volumes:
  data:
  logs: