apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    app: story-app
  ports:
    - protocol: 'TCP'
      port: 80 #outside port container
      targetPort: 3000  #port inside container
  type: LoadBalancer